services:
  db:
    image: postgres:17.2
    container_name: postgres-db
    environment:
      - POSTGRES_DB=${DB_NAME:-social}
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-adminpass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT:-5432}:5432

volumes:
  postgres_data:
    driver: local
